# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3e9ff2cf6fb3504f89dd3b9a83e2eb348ec7cbb2ca7c17435cf5bf1b4b068a079c67f98d29c7f7e5d71687edb54cff43ba5f5a606fd2f31042748be43d130199

test:
  secret_key_base: 0884fe452e9b4aee2b40568a9e392cb4441783c2531008d7dbe7b58cda2abf5c6e73a9119ba60c988c22e1b4c6f55188ba65b70309865d698e2da2cbf0396530

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
